### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Craigzyc** [ericbarch/socket-tunnel#1]
Is there anything that can be done to speed this up? Should it be significantly slower than a regular proxy?

Im getting page load times in the area of 30 seconds when I can proxy in 2 to the same host.

**Comment by iperevozchikov** [comment]
@Craigzyc Hi! See my pull request. I also had a problem with performance and solved it by replacing bouncy library on plain HTTP server.

**Comment by ericbarch** [comment]
Merged. Thanks for the contribution!
