### ISSUE TITLE
proxy und https, wss

### ISSUE THREAD

**Issue by penguine** [ericbarch/socket-tunnel#12]
I have expanded your code. socket-tunnel can use over proxy and with https now.
Should I make a pull request? Or should I send you here the lines of codes?
I haven´t use github so often. :-)

**Comment by Craigzyc** [comment]
@penguine 
please post or create a pull request so we can see it

**Comment by penguine** [comment]
for the proxy config, I only have changed the client.js:
----------------------------------
'use strict';

const IDLE_SOCKET_TIMEOUT_MILLISECONDS = 1000 * 30;

module.exports = (options) => {
  return new Promise((resolve, reject) => {
    // require the things we need
    const perf = require('execution-time')();
    const net = require('net');
    const Debug = require('debug');
    const debug = Debug('client:debug');
    const info = Debug('client:info');
    const ss = require('socket.io-stream');
    process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
    const HttpProxyAgent = require("https-proxy-agent");
    const agent = new HttpProxyAgent('http://134.168.1.43:3128');
    let socket = require('socket.io-client')(options['server'], {secure: true, reconnection: true, rejectUnauthorized: false, upgrade: false});

......

**Comment by Craigzyc** [comment]
@penguine 
According to the code you posted you initiate an agent, then don't use it. Doesn't seem to be using the proxy at all.

```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
```
Why would you try to set an environment variable?

If you want to actually use a proxy agent you need to pass it to the socket.io-client
```
const ss = require('socket.io-stream');
const HttpProxyAgent = require("https-proxy-agent");
const agent = new HttpProxyAgent('http://134.168.1.43:3128');
let socket = require('socket.io-client')(options['server'], {agent: agent, secure: true, reconnection: true, rejectUnauthorized: false, upgrade: false});
```
like so, but this has nothing at all to do with socket-tunnel, you can do this in your own code, then pass those options to the constructor

I'm also not quite sure why you would ever do that as in order for it to work as you've shown the server has to be public facing so you are just insecurely proxying to an untrusted server just to redirect to your encrypted server. 
socket.io-stream work directly with https with no modifications and no need for a proxy.

Please close the issue

**Comment by penguine** [comment]
the stream is secure. In some cases you have to go over a proxy. Then you need this config.

**Comment by Craigzyc** [comment]
Based on the config you sent it would be exposing the stream in an insecure manner unless you were just including this insecure proxy as an example 'http://134.168.1.43:3128', either way the code you provided doesn't actually use the agent so therefore doesn't use the proxy at all and would remain secure as long as the socket-tunnel server was encrpyted. 
I'm still not quite sure why you would ever use a proxy. The entire idea of this project is to not need to do that. The server needs to be public facing, thats it.

If you had a valid use case for a proxy, it would be better to set it up in your project code so it doesn't break anything with socket-tunnel and is truly optional.

```
module.exports = (options) => {
  return new Promise((resolve, reject) => {
    // require the things we need
    const net = require('net');
    const ss = require('socket.io-stream');
    const additionalOptions = options.socketOptions  || null;
    let socket = require('socket.io-client')(options['server'], additionalOptions);
```

This way you can pass in any of the options that sockt.io-client support including the agent.

Very curious tho where and when you could need a proxy agent
