### ISSUE TITLE
Add socket-tunnel to npm

### ISSUE THREAD

**Issue by alex-controlx** [ericbarch/socket-tunnel#7]
Any plans adding socket-tunnel to npm? So we can use `npm install socket-tunnel`

**Comment by tuanngocptn** [comment]
I don't think socket-tunnel should go to npm. Cuz  this is self hosted sever. And You can't share your host to everyone on global internet.

**Comment by tuanngocptn** [comment]
After several day working with this issue I just deploy npm lib to my repository. You can check and use that with script
```zsh
npm install -g git+https://github.com/tuanngocptn/socket-tunnel.git
```

**Comment by alex-controlx** [comment]
Nice, thanks for doing this.
